version: '3'
services:

  postgres:
    image: postgres:10.16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: thibaut
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nousagi
    volumes:
      - pgsql-volume-container:/var/lib/mysql
    ports:
      - 5432:5432
    networks:
      - nousagi-network

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8086:8080
    networks:
      - nousagi-network

networks:
  nousagi-network:

volumes:
  pgsql-volume-container:
